package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

//@Controller	// This means that this class is a Controller
@RestController
@RequestMapping(path="/v1") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	
	@Autowired
	private EmpresasRepository empresasRepository;
	
	@Autowired
	private LojaRepository lojaRepository;



	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@CrossOrigin
	@GetMapping(path="/empresa") // Map ONLY POST Requests
	public @ResponseBody  Iterable<Empresas>getEmpresa(@RequestParam String token) {
	
		return empresasRepository.findByToken(token);
	}
	
	@CrossOrigin
	@GetMapping(path="/loja") // Map ONLY POST Requests
	public @ResponseBody  Iterable<Loja> getAllLoja(@RequestParam String token) {
		
		Empresas emp2 = new Empresas();
		 Iterable<Empresas> emp = empresasRepository.findByToken(token);
		 for(Empresas s: emp){
				emp2 = s;
			}
	
		
		return lojaRepository.findByidempresa(emp2.getId());
	}
	
	
	
}
